export const FETCH_PINS_REQUEST = 'FETCH_PINS_REQUEST'
export const FETCH_PINS_SUCCESS = 'FETCH_PINS_SUCCESS'
export const FETCH_PINS_FAIL = 'FETCH_PINS_FAIL'

export const PIN_DETAILS_REQUEST = 'PIN_DETAILS_REQUEST'
export const PIN_DETAILS_SUCCESS = 'PIN_DETAILS_SUCCESS'
export const PIN_DETAILS_FAIL = 'PIN_DETAILS_FAIL'
export const PIN_DETAILS_RESET = 'PIN_LIKE_RESET'

export const PIN_LIKE_REQUEST = 'PIN_LIKE_REQUEST'
export const PIN_LIKE_SUCCESS = 'PIN_LIKE_SUCCESS'
export const PIN_LIKE_FAIL = 'PIN_LIKE_FAIL'
export const PIN_LIKE_RESET = 'PIN_LIKE_RESET'

export const PIN_COLLECTION_CREATE_REQUEST = 'PIN_COLLECTION_CREATE_REQUEST'
export const PIN_COLLECTION_CREATE_SUCCESS = 'PIN_COLLECTION_CREATE_SUCCESS'
export const PIN_COLLECTION_CREATE_FAIL = 'PIN_COLLECTION_CREATE_FAIL'
export const PIN_COLLECTION_CREATE_RESET = 'PIN_COLLECTION_CREATE_RESET'

