export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_COLLECTIONS_REQUEST = 'USER_COLLECTIONS_REQUEST'
export const USER_COLLECTIONS_SUCCESS = 'USER_COLLECTIONS_SUCCESS'
export const USER_COLLECTIONS_FAIL = 'USER_COLLECTIONS_FAIL';

export const USER_SAVE_PIN_REQUEST = 'USER_SAVE_PIN_REQUEST'
export const USER_SAVE_PIN_SUCCESS = 'USER_SAVE_PIN_SUCCESS'
export const USER_SAVE_PIN_FAIL = 'USER_SAVE_PIN_FAIL';

export const USER_SAVED_PINS_REQUEST = 'USER_SAVED_PINS_REQUEST'
export const USER_SAVED_PINS_SUCCESS = 'USER_SAVED_PINS_SUCCESS'
export const USER_SAVED_PINS_FAIL = 'USER_SAVED_PINS_FAIL';
